// Generated by CoffeeScript 1.6.3
(function() {
  var consonants, generate_name, rnd, _;

  _ = require('underscore');

  rnd = require('../utils/rnd');

  consonants = _.uniq(['an', 'ta', 'res', 'lu', 'na', 'sa', 'gi', 'ta', 'ri', 'us', 'vir', 'go', 'plei', 'ades', 'sol', 'cen', 'tau', 'ry', 'ji', 'ta', 'ri', 'gel', 'tau', 'rus', 'pisc', 'es']);

  generate_name = function() {
    var l, name, r, v, _i, _len, _ref;
    l = rnd.rnd_int_between(1, 4);
    name = '';
    _ref = _.range(l);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      v = _ref[_i];
      r = rnd.rnd_int_between(0, consonants.length - 1);
      name += consonants[r];
    }
    name = name.replace('aa', 'a');
    name = name.replace('uu', 'uu');
    name = name.replace('ii', 'i');
    return name;
  };

  module.exports = {
    generate_name: generate_name
  };

}).call(this);
