// Generated by CoffeeScript 1.6.3
(function() {
  var admin_auth, auth, do_auth, errors;

  errors = require('./errors');

  do_auth = function(req, res, next, admin) {
    console.log("Running auth... [admin=" + admin + "] " + req.body.auth_email);
    if ((req.body.auth_token == null) || req.body.auth_token === "") {
      console.log('Here');
      res.json(errors.NOT_AUTHED);
      return;
    }
    if ((req.body.auth_email == null) || req.body.auth_email === "") {
      console.log('Here 2');
      res.json(errors.NOT_AUTHED);
      return;
    }
    return h2ash_auth.User.findOne({
      email: req.body.auth_email,
      token: req.body.auth_token
    }).exec(function(err, user) {
      if ((!err) && (user != null)) {
        console.log('Found ...');
        if (admin && !user.admin) {
          consoe.log('Admin right required');
          res.json(errors.NOT_AUTHED);
          return;
        }
        return user.generate_token(function() {
          return user.save(function(err, saved) {
            req.auth_user = saved;
            return next();
          });
        });
      } else {
        console.log('Not Found ...');
        return res.json(errors.NOT_AUTHED);
      }
    });
  };

  auth = function(req, res, next) {
    return do_auth(req, res, next, false);
  };

  admin_auth = function(req, res, next) {
    return do_auth(req, res, next, true);
  };

  module.exports = {
    auth: auth,
    admin_auth: admin_auth
  };

}).call(this);
