// Generated by CoffeeScript 1.6.3
(function() {
  var mongoose, open_db, _;

  _ = require('underscore');

  mongoose = require('mongoose');

  open_db = function(db_name, schemas_to_register, on_open) {
    var conn, db_context, key, _i, _len, _ref;
    conn = mongoose.createConnection(db_name);
    db_context = {
      conn: conn
    };
    _ref = _.keys(schemas_to_register);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      db_context[key] = conn.model(key, schemas_to_register[key]);
    }
    conn.on('error', console.error.bind(console, 'connection error:'));
    conn.once('open', function() {
      return on_open(db_context);
    });
    return db_context;
  };

  module.exports = {
    open_db: open_db
  };

}).call(this);
