// Generated by CoffeeScript 1.6.3
(function() {
  var crypto, generate_token;

  crypto = require('crypto');

  generate_token = function(data, cb) {
    return crypto.randomBytes(256, function(ex, buff) {
      var hash, item, token, _i, _len;
      hash = crypto.createHash('sha256');
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        item = data[_i];
        hash.update(item);
      }
      hash.update(buff);
      token = hash.digest('hex');
      return cb(null, token);
    });
  };

  module.exports = generate_token;

}).call(this);
