// Generated by CoffeeScript 1.6.3
(function() {
  var handle_CORS;

  handle_CORS = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,POST,PUT,DELETE,OPTIONS');
    res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization, Content-Length, X-Requested-With');
    if ('OPTIONS' === req.method) {
      res.send(200);
    }
    return next();
  };

  module.exports = handle_CORS;

}).call(this);
