// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    pre_registration: {
      subject: 'h2ash pre-registration ... <%= token %>',
      text: 'Your pre-registration validation link is : <%= link %><%= token %>',
      html: 'Your pre-registration validation link is : <a href="<%= link %><%= token %>">Click here</a>'
    }
  };

}).call(this);
