// Generated by CoffeeScript 1.6.3
(function() {
  var reply_with, _;

  _ = require('underscore');

  reply_with = function(req, res, error, data) {
    var reply;
    reply = _.extend({}, error);
    if (data != null) {
      reply = _.extend(reply, data);
    }
    if (req.auth_user != null) {
      reply.admin = req.auth_user.admin;
      reply.auth_token = req.auth_user.token;
    }
    return res.json(reply);
  };

  module.exports = reply_with;

}).call(this);
