// Generated by CoffeeScript 1.6.3
(function() {
  var errors, generate_token, reply_with;

  errors = require('../support/errors');

  reply_with = require('../support/reply_with');

  generate_token = require('../support/generate_token');

  module.exports = function(app, dbs, auth_filters, route_name) {
    app.post(route_name + '/get_leads', auth_filters.admin_auth, function(req, res) {
      return dbs.h2ash_admin.Lead.find().select('email motivation validated').exec(function(err, leads) {
        return reply_with(req, res, errors.OK, {
          leads: leads
        });
      });
    });
    return console.log("admin routes loaded to [" + route_name + "]");
  };

}).call(this);
