// Generated by CoffeeScript 1.6.3
(function() {
  var Agent;

  Agent = require('../domain/agent');

  module.exports = function(app, auth) {
    app.post('/get/agents', auth, function(req, res) {
      return reply_with(req, res, errors.OK);
    });
    app.post('/create/agent', auth, function(req, res) {
      return reply_with(req, res, errors.OK);
    });
    app.post('/update/agent', auth, function(req, res) {
      return reply_with(req, res, errors.OK);
    });
    return app.post('/delete/agent', auth, function(req, res) {
      return reply_with(req, res, errors.OK);
    });
  };

}).call(this);
