// Generated by CoffeeScript 1.6.3
(function() {
  var auth_filters, errors, generate_token, reply_with;

  errors = require('../support/errors');

  reply_with = require('../support/reply_with');

  generate_token = require('../support/generate_token');

  auth_filters = require('../support/auth_filters');

  module.exports = function(app, dbs, route_name) {
    app.post(route_name + '/login', function(req, res) {
      return dbs.h2ash_auth.User.findOne({
        email: req.body.email
      }).exec(function(err, user) {
        if ((!err) && (user != null)) {
          if (!user.validated) {
            reply_with(req, res, errors.USER_NOT_VALIDATED);
            return;
          }
          if (user.check_password(req.body.password)) {
            return user.generate_token(function() {
              return user.save(function(err, saved) {
                req.auth_user = saved;
                console.log('Logged in OK');
                return reply_with(req, res, errors.OK);
              });
            });
          } else {
            return reply_with(req, res, errors.INVALID_CREDENTIALS);
          }
        } else {
          return reply_with(req, res, errors.INVALID_CREDENTIALS);
        }
      });
    });
    app.post(route_name + '/logout', auth_filters.auth, function(req, res) {
      req.auth_user.token = "";
      return req.auth_user.save(function(err, saved) {
        delete req.auth_user;
        return reply_with(req, res, errors.OK);
      });
    });
    return console.log("authentication routes loaded to [" + route_name + "]");
  };

}).call(this);
