// Generated by CoffeeScript 1.6.3
(function() {
  var Corporation;

  Corporation = require('../domain/corporation');

  module.exports = function(app, auth) {
    app.post('/get/corporations', auth, function(req, res) {
      return reply_with(req, res, errors.OK);
    });
    app.post('/create/corporation', auth, function(req, res) {
      return reply_with(req, res, errors.OK);
    });
    app.post('/rename/corporation', auth, function(req, res) {
      return reply_with(req, res, errors.OK);
    });
    return app.post('/delete/corporation', auth, function(req, res) {
      return reply_with(req, res, errors.OK);
    });
  };

}).call(this);
