// Generated by CoffeeScript 1.6.3
(function() {
  var UserSchema, async, auth_filters, errors, generate_token, mongoose, reply_with;

  async = require('async');

  mongoose = require('mongoose');

  errors = require('../support/errors');

  reply_with = require('../support/reply_with');

  generate_token = require('../support/generate_token');

  auth_filters = require('../support/auth_filters');

  UserSchema = require('../domain/user');

  module.exports = function(app, dbs, auth_filters, route_name) {
    app.post(route_name + '/start_testing_session', auth_filters.admin_auth, function(req, res) {
      return dbs.h2ash_auth.conn.close(function() {
        return dbs.h2ash_auth = db_utils.open_db("mongodb://localhost/h2ash_test", {
          'User': UserSchema
        }, function(db_context) {
          console.log('Test Database opened...');
          return db_context.conn.db.dropDatabase(function() {
            var admin_user, test_mode;
            console.log('Test Database dropped...');
            test_mode = true;
            console.log('Creating test admin');
            admin_user = new db_context.User({
              email: 'admin@h2ash.com',
              password: '123',
              admin: true,
              validated: true,
              registration_token: "",
              token: ""
            });
            return admin_user.save(function(err, saved) {
              console.log('Admin user saved');
              delete req.auth_user;
              return reply_with(req, res, errors.OK);
            });
          });
        });
      });
    });
    app.post(route_name + '/end_testing_session', function(req, res) {
      return dbs.h2ash_auth.conn.close(function() {
        return dbs.h2ash_auth = db_utils.open_db("mongodb://localhost/h2ash", {
          'User': UserSchema
        }, function(db_context) {
          var test_mode;
          console.log('Database opened...');
          test_mode = false;
          delete req.auth_user;
          return reply_with(req, res, errors.OK);
        });
      });
    });
    return console.log("test routes loaded to [" + route_name + "]");
  };

}).call(this);
