// Generated by CoffeeScript 1.6.3
(function() {
  var Actor, ActorSchema, mongoose;

  mongoose = require('mongoose');

  ActorSchema = mongoose.Schema({
    race: String,
    clan: String,
    faction: String,
    name: String,
    surname: String,
    skills: [],
    assignment: [],
    location: []
  });

  Actor = mongoose.model('Actor', ActorSchema);

  module.exports = Actor;

}).call(this);
