// Generated by CoffeeScript 1.6.3
(function() {
  var Corporation, CorporationSchema, User, mongoose;

  mongoose = require('mongoose');

  User = require('./user');

  CorporationSchema = mongoose.Schema({
    user: {
      type: mongoose.Schema.ObjectId,
      ref: 'User'
    },
    name: String,
    ceo: String
  });

  Corporation = mongoose.model('Corporation', CorporationSchema);

  module.exports = Corporation;

}).call(this);
