// Generated by CoffeeScript 1.6.3
(function() {
  var Moon, MoonSchema, mongoose;

  mongoose = require('mongoose');

  MoonSchema = mongoose.Schema({
    planet: {
      type: mongoose.Schema.ObjectId,
      ref: 'Planet'
    },
    name: String,
    radius: Number,
    distance: Number,
    temperature: Number,
    orbital_period: Number,
    density: Number,
    mass: Number,
    gravity: Number
  });

  Moon = mongoose.model('Moon', MoonSchema);

  module.exports = Moon;

}).call(this);
