// Generated by CoffeeScript 1.6.3
(function() {
  var User, admin_auth, app, auth, db, do_auth, errors, express, http, mongoose, reply_with, test_mode, __;

  express = require('express');

  http = require('http');

  mongoose = require('mongoose');

  __ = require('underscore');

  errors = require('./support/errors');

  User = require('./domain/user');

  app = express();

  app.set('port', process.env.PORT || 3000);

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(express.cookieParser('someVerySecretSecret123%%%4'));

  app.use(express.session());

  app.use(app.router);

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  mongoose.connect('mongodb://localhost/h2ash');

  db = mongoose.connection;

  db.on('error', console.error.bind(console, 'connection error:'));

  db.once('open', function() {
    return console.log('DB Open...');
  });

  test_mode = false;

  do_auth = function(req, res, next, admin) {
    console.log("Running auth... [admin=" + admin + "] " + req.body.auth_email);
    if ((req.body.auth_token == null) || req.body.auth_token === "") {
      console.log('Here');
      res.json(errors.NOT_AUTHED);
      return;
    }
    if ((req.body.auth_email == null) || req.body.auth_email === "") {
      console.log('Here 2');
      res.json(errors.NOT_AUTHED);
      return;
    }
    return User.findOne({
      email: req.body.auth_email,
      token: req.body.auth_token
    }).exec(function(err, user) {
      if ((!err) && (user != null)) {
        console.log('Found ...');
        if (admin && !user.admin) {
          consoe.log('Admin right required');
          res.json(errors.NOT_AUTHED);
          return;
        }
        return user.generate_token(function() {
          return user.save(function(err, saved) {
            req.auth_user = saved;
            return next();
          });
        });
      } else {
        console.log('Not Found ...');
        return res.json(errors.NOT_AUTHED);
      }
    });
  };

  auth = function(req, res, next) {
    return do_auth(req, res, next, false);
  };

  admin_auth = function(req, res, next) {
    return do_auth(req, res, next, true);
  };

  reply_with = function(req, res, error, data) {
    var reply;
    reply = __.extend({}, error);
    if (data != null) {
      reply = __.extend(reply, data);
    }
    if (req.auth_user != null) {
      reply.auth_token = req.auth_user.token;
    }
    console.log(reply);
    return res.json(reply);
  };

  app.post('/start_testing_session', admin_auth, function(req, res) {
    return db.close(function() {
      mongoose.connect('mongodb://localhost/h2ash_test');
      db = mongoose.connection;
      db.on('error', console.error.bind(console, 'connection error:'));
      return db.once('open', function() {
        return mongoose.connection.db.dropDatabase(function() {
          var admin_user;
          console.log('Test DB Open');
          console.log('Creating test admin');
          test_mode = true;
          admin_user = new User({
            email: 'admin@h2ash.com',
            password: '123',
            admin: true,
            validated: true,
            registration_token: "",
            token: ""
          });
          return admin_user.save(function(err, saved) {
            console.log('Admin user saved');
            delete req.auth_user;
            return reply_with(req, res, errors.OK);
          });
        });
      });
    });
  });

  app.post('/end_testing_session', function(req, res) {
    return db.close(function() {
      mongoose.connect('mongodb://localhost/h2ash');
      db = mongoose.connection;
      db.on('error', console.error.bind(console, 'connection error:'));
      return db.once('open', function() {
        console.log('Live DB Open');
        test_mode = false;
        delete req.auth_user;
        return reply_with(req, res, errors.OK);
      });
    });
  });

  app.post('/login', function(req, res) {
    return User.findOne({
      email: req.body.email
    }).exec(function(err, user) {
      if ((!err) && (user != null)) {
        if (!user.validated) {
          reply_with(req, res, errors.USER_NOT_VALIDATED);
          return;
        }
        if (user.check_password(req.body.password)) {
          return user.generate_token(function() {
            return user.save(function(err, saved) {
              req.auth_user = saved;
              console.log('Logged in OK');
              return reply_with(req, res, errors.OK);
            });
          });
        } else {
          return reply_with(req, res, errors.INVALID_CREDENTIALS);
        }
      } else {
        return reply_with(req, res, errors.INVALID_CREDENTIALS);
      }
    });
  });

  app.post('/logout', auth, function(req, res) {
    req.auth_user.token = "";
    return req.auth_user.save(function(err, saved) {
      delete req.auth_user;
      return reply_with(req, res, errors.OK);
    });
  });

  app.post('/overview', auth, function(req, res) {
    return reply_with(req, res, errors.OK, {
      action_points: 10
    });
  });

  app.post('/register', function(req, res) {
    return User.findOne({
      email: req.body.email
    }).exec(function(err, user) {
      var new_user;
      if ((!err) && (user != null) && user.validated) {
        console.log("User " + req.body.email + " already exists");
        return reply_with(req, res, errors.DUPLICATE_USER);
      } else if ((!err) && (user != null) && (!user.validated)) {
        return user.generate_registration_token(function() {
          if (test_mode) {
            user.registration_token = req.body.email;
          }
          return user.save(function(err, saved) {
            console.log('new user saved (Updated)');
            return reply_with(req, res, errors.OK);
          });
        });
      } else if ((!err) && !(user != null)) {
        console.log('creating new user');
        new_user = new User({
          email: req.body.email,
          password: req.body.password,
          validated: false
        });
        return new_user.generate_registration_token(function() {
          if (test_mode) {
            new_user.registration_token = req.body.email;
          }
          return new_user.save(function(err, saved) {
            console.log('new user saved');
            return reply_with(req, res, errors.OK);
          });
        });
      }
    });
  });

  app.get('/validate/:registration_token', function(req, res) {
    return User.findOne({
      registration_token: req.params.registration_token
    }).exec(function(err, user) {
      if ((!err) && (user != null)) {
        console.log('Registration token found');
        user.validated = true;
        user.registration_token = "";
        return user.save(function(err, saved) {
          console.log("User validated");
          return reply_with(req, res, errors.OK);
        });
      } else {
        console.log("Token not found. Returning OK to client.");
        return reply_with(req, res, errors.OK);
      }
    });
  });

  require('./routes/corporation_routes')(app, auth);

  app.post('/status', function(req, res) {
    return reply_with(req, res, errors.OK, {
      status: 'OK'
    });
  });

  /*
  # REST  
  #
  app.get '/projects', auth, (req,res) ->
    console.log req.session.user.projects
    res.json req.session.user.projects
  
  app.get '/categories', (req,res) ->
    ret_val = [{key:'option_1',value:'option_1_value'},{key:'option_2',value:'option_2_value'}]
    res.json(ret_val);
  
  app.get '/sub_categories/:category', (req,res) ->
    console.log req.params.category
    if req.params.category == 'option_1'
      ret_val = [{key:'option_1',value:'option_1_value_1'},{key:'option_2',value:'option_1_value_2'}]
    if req.params.category == 'option_2'
      ret_val = [{key:'option_1',value:'option_2_value_1'},{key:'option_2',value:'option_2_value_2'}]
    res.json(ret_val);
  
  
  
  app.post '/models', (req,res) ->
    new_map = mapper.create mapper_maps.map_map,req.body
    store.save local_store,js_store,mapper_maps.map_map,new_map,(saved_map)->
      res.json(saved_map)   
  
  app.get '/models', (req,res) ->
    store.load_all local_store,js_store,mapper_maps.map_map,(loaded_maps) ->
      ##console.log loaded_maps
      res.json(loaded_maps)
  
  app.delete '/models', (req,res) ->
    console.log req.query.id
    res.json({})
  */


  http.createServer(app).listen(app.get('port'), function() {
    return console.log('Express(h2ash) server listening on port ' + app.get('port'));
  });

}).call(this);
