// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var app_setup, args, http, test_mode, _,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  _ = require('underscore');

  http = require('http');

  app_setup = require('./app');

  test_mode = false;

  args = process.argv.splice(2);

  if (__indexOf.call(args, '-t') >= 0) {
    test_mode = true;
  }

  app_setup(test_mode, function(app, dbs) {
    return http.createServer(app).listen(app.get('port'), function() {
      return console.log('Express(h2ash) server listening on port ' + app.get('port'));
    });
  });

}).call(this);
