// Generated by CoffeeScript 1.6.3
(function() {
  var LeadSchema, mongoose;

  mongoose = require('mongoose');

  LeadSchema = mongoose.Schema({
    email: String,
    motivation: String,
    validated: Boolean,
    validation_token: String,
    date: {
      type: Date,
      "default": Date.now
    }
  });

  module.exports = LeadSchema;

}).call(this);
