// Generated by CoffeeScript 1.6.3
(function() {
  var app_setup, async, errors, expect, mongoose, request, should, _;

  _ = require('underscore');

  should = require('chai').should();

  expect = require('chai').expect;

  request = require('supertest');

  mongoose = require('mongoose');

  async = require('async');

  app_setup = require('../app');

  errors = require('../support/errors');

  describe('Admin process', function() {
    var app, dbs;
    app = {};
    dbs = {};
    before(function(done) {
      return app_setup(true, function(test_app, test_dbs) {
        app = test_app;
        dbs = test_dbs;
        return async.series([
          function(cb) {
            var admin;
            admin = dbs.h2ash_auth.User({
              email: 'admin@h2ash.com',
              password: '123',
              admin: true,
              validated: true,
              registration_token: "",
              token: ""
            });
            return admin.save(function(err, res) {
              return cb(null, '');
            });
          }, function(cb) {
            var lead;
            lead = dbs.h2ash_admin.Lead({
              email: 'lead1@here.com',
              motivation: 'I like games',
              validated: false
            });
            return lead.save(function(err, res) {
              return cb(null, '');
            });
          }, function(cb) {
            var lead;
            lead = dbs.h2ash_admin.Lead({
              email: 'lead2@here.com',
              motivation: 'Let me test ....',
              validated: true
            });
            return lead.save(function(err, res) {
              return cb(null, '');
            });
          }
        ], function() {
          return done();
        });
      });
    });
    return describe('get_leads', function() {
      return it('should load all the leads', function(done) {
        var token;
        token = '';
        return async.series([
          function(cb) {
            return request(app).post("/authentication/login").send({
              email: 'admin@h2ash.com',
              password: '123'
            }).end(function(err, res) {
              var json;
              json = JSON.parse(res.text);
              token = json.auth_token;
              return cb(null, '');
            });
          }, function(cb) {
            return request(app).post("/admin/get_leads").send({
              auth_email: 'admin@h2ash.com',
              auth_token: token
            }).end(function(err, res) {
              var json;
              res.status.should.equal(200);
              json = JSON.parse(res.text);
              json.error_code.should.equal(errors.OK.error_code);
              json.error_message.should.equal(errors.OK.error_message);
              json.leads.length.should.equal(2);
              done();
              return cb(null, '');
            });
          }
        ]);
      });
    });
  });

}).call(this);
