// Generated by CoffeeScript 1.6.3
(function() {
  var app_setup, expect, mongoose, request, should, _;

  _ = require('underscore');

  should = require('chai').should();

  expect = require('chai').expect;

  request = require('supertest');

  mongoose = require('mongoose');

  app_setup = require('../app');

  describe('Pre-Registration', function() {
    var app, dbs;
    app = {};
    dbs = {};
    before(function(done) {
      return app_setup(true, function(test_app, test_dbs) {
        app = test_app;
        dbs = test_dbs;
        return done();
      });
    });
    return describe('register', function() {
      it('should create a new lead in the admin database', function(done) {
        return request(app).post("/pre_registration/register").send({
          email: 'me@here.com',
          motivation: 'Because I like space games.'
        }).end(function(err, res) {
          var json;
          res.status.should.equal(200);
          json = JSON.parse(res.text);
          json.error_code.should.equal(0);
          json.error_message.should.equal('');
          return dbs.h2ash_admin.Lead.find({
            email: 'me@here.com'
          }).exec(function(err, res) {
            should.exist(res);
            res.length.should.equal(1);
            res[0].email.should.equal('me@here.com');
            res[0].should.have.property('validation_token')["with"].length(256 / 4);
            return done();
          });
        });
      });
      return it('should not add duplicates', function(done) {
        return request(app).post("/pre_registration/register").send({
          email: 'me@here.com',
          motivation: 'Because I like space games.'
        }).end(function(err, res) {
          var json;
          res.status.should.equal(200);
          json = JSON.parse(res.text);
          return dbs.h2ash_admin.Lead.find({
            email: 'me@here.com'
          }).exec(function(err, res) {
            should.exist(res);
            res.length.should.equal(1);
            return done();
          });
        });
      });
    });
  });

}).call(this);
