// Generated by CoffeeScript 1.6.3
(function() {
  var app_setup, expect, request, should, _;

  _ = require('underscore');

  should = require('chai').should();

  expect = require('chai').expect;

  request = require('supertest');

  app_setup = require('../app');

  describe('Connectors', function() {
    var app;
    app = {};
    before(function(done) {
      return app_setup(true, function(local_app) {
        app = local_app;
        return done();
      });
    });
    describe('create', function() {
      return it("???????", function(done) {
        return request(app).post("/status").send({}).expect(404, {}, done);
      });
    });
    return describe('create', function() {
      return it("should return a 400 error if there is no type specified", function(done) {
        return request(app).get("/status").send({}).expect(200).expect(function(res) {
          return res.text.status.should.equal("OK");
        }).end(function(err, res) {
          return done();
        });
      });
    });
  });

}).call(this);
