// Generated by CoffeeScript 1.6.3
(function() {
  var UserSchema, async, db_utils, dbs;

  async = require('async');

  UserSchema = require('../domain/user');

  db_utils = require('../support/db_utils');

  dbs = {};

  async.parallel([
    function(cb) {
      return dbs.h2ash_auth = db_utils.open_db("mongodb://localhost/h2ash_auth", {
        'User': UserSchema
      }, function(db_context) {
        console.log("Database opened...[" + db_context.conn.name + "]");
        return db_context.conn.db.dropDatabase(function() {
          console.log("Database dropped...[" + db_context.conn.name + "]");
          return cb(null, '');
        });
      });
    }
  ], function() {
    var admin_user;
    admin_user = new dbs.h2ash_auth.User({
      email: 'admin@h2ash.com',
      password: '123',
      admin: true,
      validated: true,
      registration_token: "",
      token: ""
    });
    return admin_user.save(function(err, saved_user) {
      if (err) {
        console.log(err);
      } else {
        console.log("Saved user [" + saved_user.email + "]");
      }
      return dbs.h2ash_auth.conn.close();
    });
  });

}).call(this);
