// Generated by CoffeeScript 1.6.3
(function() {
  var THREE, check_vector, expect, movement, new_movable, should, _;

  _ = require('underscore');

  THREE = require('three');

  should = require('chai').should();

  expect = require('chai').expect;

  movement = require('../../utils/movement');

  new_movable = function() {
    var direction, max_angular_speed, max_speed, o, position;
    position = new THREE.Vector3();
    direction = new THREE.Vector3(1, 0, 0);
    max_speed = 1;
    max_angular_speed = Math.PI / 180;
    o = new movement.Movable(position, direction, max_speed, max_angular_speed, 0);
    return o;
  };

  check_vector = function(v, x, y, z) {
    v.x.should.equal(x);
    v.y.should.equal(y);
    return v.y.should.equal(z);
  };

  describe('movement', function() {
    return describe('movement.update', function() {
      return describe('movement where no rotation is involved', function() {
        var o;
        o = new_movable();
        o.set_target_position(new THREE.Vector3(100, 0, 0));
        it('should move to (1,0,0) ', function() {
          o.set_speed(1);
          o.update(1000);
          check_vector(o.position, 1, 0, 0);
          return o.last_update.should.equal(1000);
        });
        return it('should move to (1.5,0,0) ', function() {
          o.set_speed(0.5);
          o.update(2000);
          check_vector(o.position, 1.5, 0, 0);
          return o.last_update.should.equal(2000);
        });
      });
    });
  });

}).call(this);
