// Generated by CoffeeScript 1.6.3
(function() {
  var rough_size_of_object, _;

  _ = require('underscore');

  rough_size_of_object = function(object) {
    var bytes, i, key, objectList, stack, value, _i, _j, _len, _len1, _ref;
    objectList = [];
    stack = [object];
    bytes = 0;
    while (stack.length) {
      value = stack.pop();
      if (_.isBoolean(value)) {
        bytes += 4;
      } else if (_.isString(value)) {
        bytes += value.length * 2;
      } else if (_.isNumber(value)) {
        bytes += 8;
      } else if (_.isArray(value)) {
        for (_i = 0, _len = value.length; _i < _len; _i++) {
          i = value[_i];
          stack.push(value[i]);
        }
      } else if (_.isObject(value) && objectList.indexOf(value) === -1) {
        objectList.push(value);
        _ref = _.keys(value);
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          key = _ref[_j];
          stack.push(value[key]);
        }
      }
    }
    return bytes;
  };

  module.exports = {
    rough_size_of_object: rough_size_of_object
  };

}).call(this);
