// Generated by CoffeeScript 1.6.3
(function() {
  var fix_value, lcg_parm, rand, random, restore, rnd, rnd_float_between, rnd_int_between, srand, _, _saved;

  _ = require('underscore');

  lcg_parm = {
    seed: new Date().getTime(),
    a: 1103515245,
    c: 12345,
    m: Math.pow(2, 32)
  };

  srand = function(seed) {
    return lcg_parm.seed = seed;
  };

  rand = function() {
    lcg_parm.seed = (lcg_parm.a * lcg_parm.seed + lcg_parm.c) % lcg_parm.m;
    return lcg_parm.seed;
  };

  random = function() {
    return rand() / lcg_parm.m;
  };

  rnd = function() {
    return random();
  };

  rnd_float_between = function(min, max) {
    var delta, r;
    r = rnd();
    delta = max - min;
    return min + delta * r;
  };

  rnd_int_between = function(min, max) {
    var count, i, prob, r, total_prob, _i, _len, _ref;
    count = max - min + 1;
    prob = 1 / count;
    total_prob = prob;
    r = rnd();
    _ref = _.range(count);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      if (r <= total_prob) {
        return min + i;
      } else {
        total_prob += prob;
      }
    }
    return min + count - 1;
  };

  _saved = random;

  fix_value = function(value) {
    return random = function() {
      return value;
    };
  };

  restore = function() {
    return random = _saved;
  };

  module.exports = {
    srand: srand,
    rand: rand,
    random: random,
    rnd: rnd,
    rnd_float_between: rnd_float_between,
    rnd_int_between: rnd_int_between,
    fix_value: fix_value,
    restore: restore
  };

}).call(this);
